### ISSUE TITLE
No manifest for linux/arm64/v8

### ISSUE THREAD

**Issue by kevinholtkamp** [hypriot/rpi-mysql#21]
When installing this container on my raspberrypi, i get the following error:
`docker: no matching manifest for linux/arm64/v8 in the manifest list entries.`

`uname -m` gives me the following output:
`aarch64`

I don't know a lot about docker or linux, but is the problem that my pi is on a 64 bit OS?

**Comment by firecyberice** [comment]
Please use the docker.io/library/mysql image instead.
