### ISSUE TITLE
Exectue sh/sql/sql.gz Files

### ISSUE THREAD

**Issue by Tsumiqt** [hypriot/rpi-mysql#7]
Like the official MySQL Docker Image this Images should be able to execute Files from within /docker-entrypoint-initdb.d/*

**Comment by firecyberice** [comment]
Feel free to adapt the official mysql Dockerfile and provide a PR

**Comment by Tsumiqt** [comment]
I just created a pull request: [PR:8](https://github.com/hypriot/rpi-mysql/pull/8)
It works different to the official mysql docker image because they execute it right away. I appended all the sql files to the existing tempSqlFile wich is executed as --init-file.

**Comment by StefanScherer** [comment]
Thanks @Tsumiqt
